from __future__ import annotations

import sys
from pathlib import Path

SCRIPTS_DIR = Path(__file__).resolve().parent / 'scripts'
if str(SCRIPTS_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPTS_DIR))

strategy_module = __import__('binance_futures_momentum_long')
runtime_store_module = __import__('runtime_store')
request_manager_module = __import__('binance_request_manager')
trade_bucket_analysis_module = __import__('trade_bucket_analysis')
slippage_calibration_policy_module = __import__('slippage_calibration_policy')
install_execution_feedback_hardening = __import__('execution_feedback_hardening').install_execution_feedback_hardening
install_lifecycle_snapshot_hooks = __import__('lifecycle_snapshot').install_lifecycle_snapshot_hooks
install_reduce_only_risk_guard = __import__('risk_exit_guard').install_reduce_only_risk_guard
install_rest_guard_retry_after_hardening = __import__('rest_guard_retry_after_hardening').install_rest_guard_retry_after_hardening
install_runtime_state_backup_hardening = __import__('runtime_state_backup_hardening').install_runtime_state_backup_hardening
install_runtime_state_hardening = __import__('runtime_state_hardening').install_runtime_state_hardening
install_request_throttle_hardening = __import__('request_throttle_hardening').install_request_throttle_hardening
install_selection_quality_hook = __import__('selection_quality_policy').install_selection_quality_hook
install_slippage_cache_staleness_hardening = __import__('slippage_cache_staleness_hardening').install_slippage_cache_staleness_hardening
install_slippage_calibration_hooks = slippage_calibration_policy_module.install_slippage_calibration_hooks
install_trade_bucket_slippage_hardening = __import__('trade_bucket_slippage_hardening').install_trade_bucket_slippage_hardening
install_runtime_state_hardening(runtime_store_module)
install_runtime_state_backup_hardening(runtime_store_module)
install_request_throttle_hardening(request_manager_module)
install_rest_guard_retry_after_hardening(strategy_module)
install_execution_feedback_hardening(strategy_module)
install_lifecycle_snapshot_hooks(strategy_module)
install_reduce_only_risk_guard(strategy_module)
install_trade_bucket_slippage_hardening(trade_bucket_analysis_module)
install_slippage_cache_staleness_hardening(slippage_calibration_policy_module)
install_selection_quality_hook(strategy_module)
install_slippage_calibration_hooks(strategy_module)
strategy_main = strategy_module.main


if __name__ == '__main__':
    raise SystemExit(strategy_main())
